### ISSUE TITLE
com.google.android.gms.dynamic.zzg$zza: Could not get remote context

### ISSUE THREAD

**Issue by awpss** [googlesamples/android-vision#10]
com.google.android.gms.samples.vision.face.photo E/FaceDetectorHandle﹕ Could not create native face detector
    com.google.android.gms.dynamic.zzg$zza: Could not get remote context.
            at com.google.android.gms.dynamic.zzg.zzar(Unknown Source)
            at com.google.android.gms.vision.face.internal.client.zzf.zzb(Unknown Source)
            at com.google.android.gms.vision.face.internal.client.zzf.zza(Unknown Source)
            at com.google.android.gms.vision.face.internal.client.zzg.zzCg(Unknown Source)
            at com.google.android.gms.vision.face.internal.client.zzg.zzb(Unknown Source)
            at com.google.android.gms.vision.face.FaceDetector.detect(Unknown Source)
            at com.google.android.gms.samples.vision.face.photo.PhotoViewerActivity.onCreate(PhotoViewerActivity.java:63)
            at android.app.Activity.performCreate(Activity.java:5249)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5047)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by pm0733464** [comment]
I would guess that your device doesn't have a current version of Google Play services.  You can see the version by going to Settings > Apps > All > Google Play services.  The version should be 7.8.95 or greater.

**Comment by vinaykumar2491** [comment]
I'm also having the same issues. My device has the latest Google Play services installed, but still the app crashes.

**Comment by pm0733464** [comment]
Please give the Google Play services version and the crash output that you are getting.

**Comment by vinaykumar2491** [comment]
Google Play Services Version : 8.3.0

Stack Trace:
 E/FaceDetectorHandle: Could not create native face detector
                                                       com.google.android.gms.dynamic.zzg$zza: Could not get remote context.
                                                           at com.google.android.gms.dynamic.zzg.zzaA(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzf.zzb(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzf.zza(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzg.zzGn(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzg.<init>(Unknown Source)
                                                           at com.google.android.gms.vision.face.FaceDetector$Builder.build(Unknown Source)
                                                           at com.cognizant.uxlab.luna.PageFragment.onCreateView(PageFragment.java:63)
                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                           at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                           at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                                                           at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                       	at android.view.Choreographer.doFrame(Choreographer.ja
12-30 10:01:10.730 10539-10539/? W/FaceDetectorHandle: Native face detector not yet available.  Reverting to no-op detection.
12-30 10:01:10.779 10539-10539/? E/FaceDetectorHandle: Could not create native face detector
                                                       com.google.android.gms.dynamic.zzg$zza: Could not get remote context.
                                                           at com.google.android.gms.dynamic.zzg.zzaA(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzf.zzb(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzf.zza(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzg.zzGn(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzg.zzb(Unknown Source)
                                                           at com.google.android.gms.vision.face.FaceDetector.detect(Unknown Source)
                                                           at com.cognizant.uxlab.luna.PageFragment.onCreateView(PageFragment.java:65)
                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                           at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                           at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                                                           at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                           at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                       	a
12-30 10:01:10.780 10539-10539/? E/FaceDetectorHandle: Could not create native face detector
                                                       com.google.android.gms.dynamic.zzg$zza: Could not get remote context.
                                                           at com.google.android.gms.dynamic.zzg.zzaA(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzf.zzb(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzf.zza(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzg.zzGn(Unknown Source)
                                                           at com.google.android.gms.vision.face.internal.client.zzg.isOperational(Unknown Source)
                                                           at com.google.android.gms.vision.face.FaceDetector.isOperational(Unknown Source)
                                                           at com.cognizant.uxlab.luna.PageFragment.onCreateView(PageFragment.java:66)
                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                           at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                           at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                                                           at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                           at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                           at android.view.View.measure(View.java:18788)
                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                       	at android.view.Choreographer.doFrame(Choreogra
12-30 10:01:10.780 10539-10539/? W/FaceDetector: Face Detector dependencies are not available

**Comment by pm0733464** [comment]
When you say "Google Play Services Version : 8.3.0", is this the version that have on your device or the version that you are compiling your app with?  Those can be two different versions.  Please report both.

The device version can be found by navigating like this on your device: 

Settings > Apps > All > Google Play services

The compile version can be found in your build file, for example:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/FaceTracker/app/build.gradle#L25

**Comment by vinaykumar2491** [comment]
Configured the Google Play Services Version on both : device/emulator & App and its working now. 
Thanks.

**Comment by momo1986** [comment]
Met the same problem, is there a document for fix of this problem?
