### ISSUE TITLE
 Local module descriptor class for com.google.android.gms.vision.dynamite not found.

### ISSUE THREAD

**Issue by scottyyih** [googlesamples/android-vision#164]
On my device, face tracking fails with errors:
W/DynamiteModule( 1417): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 1417): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:801
I/DynamiteModule( 1417): Selected remote version of com.google.android.gms.vision.dynamite, version >= 801
W/DynamiteModule( 1417): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 1417): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:801
I/DynamiteModule( 1417): Selected remote version of com.google.android.gms.vision.dynamite, version >= 801
D/CameraHardware(  207): CameraHardware::previewThread: posting preview frame...

**Comment by liuyl** [comment]
Hi.
The "Local module descriptor class for com.google.android.gms.vision.dynamite not found" is benign, it has nothing to do with if your detector is operational or not. That's why it's a warning instead of error.

Can you check if your device is at low storage? That's the most common reason why detector doesn't work.

**Comment by scottyyih** [comment]
Thank you for your reply. But my device still has 1.57GB free space. It looks like that the module com.google.android.gms.vision.dynamite:801 need to be downloaded remotely.  And no internet access on my device

**Comment by wanamr87** [comment]
My device

**Comment by dwmolina** [comment]
Hi scottyyih.

Have you resolved the problem? I'm getting it too.

Let me know if you resolved it, please.

I'm trying to run the barcode reader app in my Xperia Z2, Android 6.0.1:

`W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:801
I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 801
W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:801
I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 801
D/Camera: app passed NULL surface
D/BarcodeMain: No barcode captured, intent data is null`

**Comment by liuyl** [comment]
Hi scottyyih.

The "remote" in this log message doesn't mean "cloud", it means Google Play Service which is already installed on your device.
If your device doesn't have internet connection, then that's the reason. The API does a download at the first time it is used.

**Comment by yinguobing** [comment]
same issue here, and establishing a internet connection successfully solved my problem.

**Comment by NalediMadlopha** [comment]
Hi there, I am getting this issue in my face detector app. Does anyone know what's the cause of it? Except the internet connection how can I resolve this issue because my device is connected to the internet when I get this issue?

**Comment by TThana** [comment]
I/Vision: libocr.so library load status: false
 Local module descriptor class for com.google.android.gms.vision.dynamite not found.

**Comment by kruyvanna** [comment]
Can't get it to work.

`07-08 16:36:29.168 4642-4642/com.google.android.gms.samples.vision.barcodereader W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
07-08 16:36:29.168 4642-4642/com.google.android.gms.samples.vision.barcodereader I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1101
07-08 16:36:29.168 4642-4642/com.google.android.gms.samples.vision.barcodereader I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 1101
07-08 16:36:29.168 4642-4642/com.google.android.gms.samples.vision.barcodereader I/Vision: Loading library libbarhopper.so
07-08 16:36:29.168 4642-4642/com.google.android.gms.samples.vision.barcodereader I/Vision: libbarhopper.so library load status: false
07-08 16:36:29.168 4642-4642/com.google.android.gms.samples.vision.barcodereader W/NativeBarcodeDetectorHandle: Native barcode detector not yet available.  Reverting to no-op detection.`

Using vision api
`compile 'com.google.android.gms:play-services-vision:11.0.2'`


Google Play Service installed
`11.0.55`

Internet Connection is available
Free space is 2.76GB

**Comment by kruyvanna** [comment]
It worked by **Clear All Data**
Wasted 4 hours :(

**Comment by vasudha1997** [comment]
Hi there, I am getting an issue with Google play store. Although I have installed Google pay services...my code is not working with an error that version is null.
W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
E/ActivityThread: Failed to find provider info for com.google.android.gms.chimera
W/DynamiteModule: Failed to retrieve remote module version.
W/GooglePlayServicesUtil: Google Play Store is missing.
I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:0
E/FaceNativeHandle: Error creating remote native handle
                    com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
                        at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
                        at com.google.android.gms.internal.fb.zzDR(Unknown Source)
                        at com.google.android.gms.vision.face.internal.client.zza.<init>(Unknown Source)
                        at com.google.android.gms.vision.face.FaceDetector$Builder.build(Unknown Source)
                        at com.example.vasudha.facedetection.MainActivity$1.onClick(MainActivity.java:55)
                        at android.view.View.performClick(View.java:4756)
                        at android.view.View$PerformClick.run(View.java:19749)
                        at android.os.Handler.handleCallback(Handler.java:739)
                        at android.os.Handler.dispatchMessage(Handler.java:95)
                        at android.os.Looper.loop(Looper.java:135)
                        at android.app.ActivityThread.main(ActivityThread.java:5221)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at java.lang.reflect.Method.invoke(Method.java:372)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/FaceNativeHandle: Native handle not yet available. Reverting to no-op handle.
W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:114)
W/System.err:     at com.example.vasudha.facedetection.MainActivity$1.onClick(MainActivity.java:60)
W/System.err:     at android.view.View.performClick(View.java:4756)
W/System.err:     at android.view.View$PerformClick.run(View.java:19749)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:135)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
D/*abcd: Google Play Store version is null
W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
W/GooglePlayServicesUtil: Google Play Store is missing.
I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:0
E/FaceNativeHandle: Error creating remote native handle
                    com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
                        at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
                        at com.google.android.gms.internal.fb.zzDR(Unknown Source)
                        at com.google.android.gms.internal.fb.isOperational(Unknown Source)
                        at com.google.android.gms.vision.face.FaceDetector.isOperational(Unknown Source)
                        at com.example.vasudha.facedetection.MainActivity$1.onClick(MainActivity.java:67)
                        at android.view.View.performClick(View.java:4756)
                        at android.view.View$PerformClick.run(View.java:19749)
                        at android.os.Handler.handleCallback(Handler.java:739)
                        at android.os.Handler.dispatchMessage(Handler.java:95)
                        at android.os.Looper.loop(Looper.java:135)
                        at android.app.ActivityThread.main(ActivityThread.java:5221)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at java.lang.reflect.Method.invoke(Method.java:372)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
V/RenderScript: 0xa5b58c00 Launching thread(s), CPUs 2
Application terminated.

**Comment by alex011235** [comment]
Restarting Android Studio worked for me. This problem usually occur when I try a new emulator.

**Comment by heru762004** [comment]
It happen only in certain phone. I think its google play service bug. I resolved by remove camera permission and re enter the application and give camera permission again.

**Comment by AngryITGuy** [comment]
Had similar problem. Loading app onto device, app runs, but google-vision not functioning. Deleting the app, doing a "Rebuild" in Android Studio then re-deploying onto device fixed the issue for me.

**Comment by arshadzya** [comment]
04-20 11:53:04.462 1474-1481/com.skymet.indianweather I/art: Thread[2,tid=1481,WaitingInMainSignalCatcherLoop,Thread*=0xb70a7528,peer=0x32c2a0a0,"Signal Catcher"]: reacting to signal 3
04-20 11:53:04.952 1474-1481/com.skymet.indianweather I/art: Wrote stack traces to '/data/anr/traces.txt'
04-20 11:53:10.512 1474-1474/com.skymet.indianweather W/ResourcesManager: getTopLevelResources: com.skymet.indianweather for user  0
04-20 11:53:10.622 1474-1474/com.skymet.indianweather I/CrashlyticsCore: Initializing Crashlytics 2.6.0.22
04-20 11:53:10.652 1474-2152/com.skymet.indianweather W/ResourcesManager: getTopLevelResources: com.google.android.gms for user  0
04-20 11:53:10.652 1474-2152/com.skymet.indianweather W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
04-20 11:53:10.652 1474-2152/com.skymet.indianweather W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
04-20 11:53:10.792 1474-1474/com.skymet.indianweather I/FA: App measurement is starting up, version: 11020
04-20 11:53:10.792 1474-1474/com.skymet.indianweather I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
04-20 11:53:10.842 1474-1474/com.skymet.indianweather I/FA: To enable faster debug mode event logging run:
                                                              adb shell setprop debug.firebase.analytics.app com.skymet.indianweather
04-20 11:53:11.082 1474-1474/com.skymet.indianweather I/CrashlyticsInitProvider: CrashlyticsInitProvider initialization successful
04-20 11:53:11.142 1474-2140/com.skymet.indianweather I/CrashlyticsCore: Registered Firebase Analytics event listener
04-20 11:53:11.362 1474-1474/com.skymet.indianweather I/FirebaseInitProvider: FirebaseApp initialization successful
04-20 11:53:11.382 1474-1474/com.skymet.indianweather E/TypefaceUtil: Can not set custom font fonts/roboto_light.ttf instead of serif
04-20 11:53:11.392 1474-2174/com.skymet.indianweather W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
04-20 11:53:11.392 1474-1474/com.skymet.indianweather D/InjectionManager: InjectionManager
04-20 11:53:11.402 1474-1474/com.skymet.indianweather D/InjectionManager: fillFeatureStoreMap com.skymet.indianweather
04-20 11:53:11.402 1474-1474/com.skymet.indianweather I/InjectionManager: Constructor com.skymet.indianweather, Feature store :{}
04-20 11:53:11.402 1474-1474/com.skymet.indianweather I/InjectionManager: featureStore :{}
04-20 11:53:11.402 1474-2177/com.skymet.indianweather I/DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:0
04-20 11:53:11.402 1474-2177/com.skymet.indianweather I/DynamiteModule: Selected local version of com.google.android.gms.flags
04-20 11:53:11.412 1474-2177/com.skymet.indianweather W/ResourcesManager: getTopLevelResources: com.google.android.gms for user  0
04-20 11:53:11.412 1474-2177/com.skymet.indianweather W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
04-20 11:53:11.412 1474-2177/com.skymet.indianweather W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
04-20 11:53:11.422 1474-2174/com.skymet.indianweather W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.

**Comment by iaubain** [comment]
Guys, after hours of challenge for me the problem was solved buy Updating Google Play Services to version (12.6.85) and I restarted the device and guess what? The app worked fine.
For updating this Google play service I followed this link
https://www.androidpit.com/install-google-play-services-apk

**Comment by eberkheev** [comment]
Check list:
1. Internet connection
Check connection
2. Storage permissions
add android:installLocation="auto" to <manifest> tag
3. Metadata
add
4. Insufficient storage

**Comment by Fizik2** [comment]
I had got same problem. All advices of this topic didn't help me. After 4 hours of research I had got a solution for me.  I resolved by remove camera permission FOR google play service and re enter the application and give camera permission for google play service again.

**Comment by aktham0** [comment]
I have the same problem I tried all solution but not work :/
pleas help me to solve this problem

**Comment by aktham0** [comment]
This my Problem : 😣
E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.

**Comment by Aminnasseri** [comment]
I have the same.
my app has worked without any problem until today but these are my errors:
04-11 10:20:16.041 15093-15093/mitofit.com.rapidkit E/Vision: Error loading module com.google.android.gms.vision.barcode optional module true: gg: No acceptable module found. Local version is 0 and remote version is 0.
04-11 10:20:16.041 15093-15093/mitofit.com.rapidkit I/Vision: Request download for engine barcode is a no-op because rate limiting
04-11 10:20:16.041 15093-15093/mitofit.com.rapidkit E/QREader: Barcode recognition libs are not downloaded and are not operational

**Comment by xzec** [comment]
I'm experiencing this error when trying to implement firebase ml vision - text recognition.

E/Vision : Error loading module com.google.android.gms.vision.ocr optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.

I tried all recommended solutions. Any progress on this?

**Comment by miladrashidizade** [comment]
hello 
My problem is as follows and I can not use OCR to read the text!
Can anyone help me?
 Local module descriptor class for com.google.android.gms.vision.dynamite.ocr not found.
I/DynamiteModule(27014): Considering local module com.google.android.gms.vision.dynamite.ocr:0 and remote module com.google.android.gms.vision.dynamite.ocr:0
W/DynamiteModule(27014): Local module descriptor class for com.google.android.gms.vision.ocr not found.
I/DynamiteModule(27014): Considering local module com.google.android.gms.vision.ocr:0 and remote module com.google.android.gms.vision.ocr:0
E/Vision  (27014): Error loading optional module com.google.android.gms.vision.ocr: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
W/DynamiteModule(27014): Local module descriptor class for com.google.android.gms.vision.dynamite.ocr not found.
I/DynamiteModule(27014): Considering local module com.google.android.gms.vision.dynamite.ocr:0 and remote module com.google.android.gms.vision.dynamite.ocr:0
W/DynamiteModule(27014): Local module descriptor class for com.google.android.gms.vision.ocr not found.
I/DynamiteModule(27014): Considering local module com.google.android.gms.vision.ocr:0 and remote module com.google.android.gms.vision.ocr:0
E/Vision  (27014): Error loading optional module com.google.android.gms.vision.ocr: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
D/skia    (27014): onFlyCompress
D/skia    (27014): SkJpegCodec::onGetPixels +
D/skia    (27014): SkJpegCodec::onGetPixels -

**Comment by PhanithNoch** [comment]
@miladrashidizade  I got the same issues did you solve it help, please

**Comment by Aminnasseri** [comment]
I didnt remember but i think i used vpn 🤔

**Comment by gyoyen** [comment]
i fixed it this way
1- i added meta-data to AndroidManifest.xml
![1](https://user-images.githubusercontent.com/83110566/115950189-82dcba80-a4e2-11eb-92af-7d6f76ec8c92.JPG)
2- i created device containing 'Google Play Service' from AVD Manager.
![2](https://user-images.githubusercontent.com/83110566/115950281-f8e12180-a4e2-11eb-84a9-986dd5094c1c.JPG)
3- i clicked 'Update Google Play Service' of the device and signed in with my google account
![3](https://user-images.githubusercontent.com/83110566/115950331-43fb3480-a4e3-11eb-977b-bb191360f636.JPG)

and work it
![4](https://user-images.githubusercontent.com/83110566/115950366-8755a300-a4e3-11eb-8185-80aeec1d4f46.JPG)

my dependencies in pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.4
  firebase_ml_vision: ^0.12.0+1
  image_picker: ^0.7.4

**Comment by julianwue** [comment]
> Check list:
> 
> 1. Internet connection
>    Check connection
> 2. Storage permissions
>    add android:installLocation="auto" to  tag
> 3. Metadata
>    add
> 
> ```
>         <meta-data
>             android:name="com.google.android.gms.version"
>             android:value="@integer/google_play_services_version" /> 
>         <meta-data
>             android:name="com.google.android.gms.vision.DEPENDENCIES"
>             android:value="barcode" /> 
> ```
> 
> 1. Insufficient storage
>    Check storage for free space

Had same issue for few weeks. Made all of this steps, and added permission INTERNET. Used barcode and ocr in DEPENDENCIES. After I checked all elements to be set, it worked in Android 10 Emulator with play store and in my real device Android 11.

**Comment by sina03030** [comment]
if updating google and other stuff did not work for you it's possible that google does not offer you this service , to make sure that google let your ip use gms service's turn on your vpn for emulator and test it with webcam ( note that google will recognize your ip on real device even with vpn ) , for me it was running perfectly on emulator (with vpn) and not working on real device because i had iran ip ...

**Comment by hassank185** [comment]
Sir i Have this problem Please If you have solution Let me Know then :


W/DynamiteModule(17808): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule(17808): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller(17808): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
I/.group_chat_ap(17808): The ClassLoaderContext is a special shared library.
I/.group_chat_ap(17808): The ClassLoaderContext is a special shared library.
I/TetheringManager(17808): registerTetheringEventCallback:com.example.group_chat_app
V/NativeCrypto(17808): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 295 native methods...
W/.group_chat_ap(17808): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
I/ProviderInstaller(17808): Installed default security provider GmsCore_OpenSSL
W/ConnectivityManager.CallbackHandler(17808): callback not found for CALLBACK_AVAILABLE message

**Comment by jlriverob** [comment]
> 2\. android:installLocation="auto"

Quisiera saber si a alguno de ustedes les ha dado este problema, me dice que W/ProviderInstaller: Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.

mientras tanto mi aplicacion no puede acceder a internet, hasta que activo y desactivo el wifi o activo y desactivo los datos del dispositivo y mi aplicacion comienza a actualizar datos y por ende a tener acceso a internet.

Ya agote todos mis conocimientos porque es algo que venia funcionando muy bien y de un momento a otro se puso en esta situacion y no he podido soucionar.

Si alguno de ustedes les ha dado este problema y si supieron como solucionarlo les estare eternamente agradecido.

Saludos y Gracias

**Comment by ranaa7** [comment]
I have this problem, If you have solution Let me know then :
W/DynamiteModule( 7762): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 7762): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 7762): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
D/ApplicationLoaders( 7762): Returning zygote-cached class loader: /system/framework/android.hidl.base-V1.0-java.jar
D/ApplicationLoaders( 7762): Returning zygote-cached class loader: /system/framework/android.hidl.manager-V1.0-java.jar
D/ApplicationLoaders( 7762): Returning zygote-cached class loader: /system/framework/android.hidl.base-V1.0-java.jar
I/.cryptocurrenc( 7762): The ClassLoaderContext is a special shared library.
I/.cryptocurrenc( 7762): The ClassLoaderContext is a special shared library.
I/chatty  ( 7762): uid=10135(com.example.cryptocurrency) AsyncTask #1 identical 1 line
I/.cryptocurrenc( 7762): The ClassLoaderContext is a special shared library.
W/ProviderInstaller( 7762): Failed to report request stats: com.google.android.gms.common.security.ProviderInstallerImpl.reportRequestStats [class android.content.Context, long, long]

**Comment by BarannUnsal** [comment]
I have this problem:

W/DynamiteModule(11248): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule(11248): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller(11248): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
I/System.out(11248): [socket]:check permission begin!

**Comment by sina03030** [comment]
Use shecan.ir dns to break sanctions
