### ISSUE TITLE
Crash when opening camera - Android version 5.0.2

### ISSUE THREAD

**Issue by eranio** [googlesamples/android-vision#228]
I get this error:
java.lang.RuntimeException: Fail to connect to camera service
                                                                                                            at android.hardware.Camera.<init>(Camera.java:641)
                                                                                                            at android.hardware.Camera.open(Camera.java:479)
                                                                                                            at com.google.android.gms.vision.CameraSource.zzchq

**Comment by Denjag** [comment]
Up!
Android 5 and Android 4:

                                                   java.lang.RuntimeException: Fail to connect to camera service
                                                       at android.hardware.Camera.<init>(Camera.java:497)
                                                       at android.hardware.Camera.open(Camera.java:342)
                                                       at com.google.android.gms.vision.CameraSource.zzchq(Unknown Source)
                                                       at com.google.android.gms.vision.CameraSource.start(Unknown Source)
                                                       at com.google.android.gms.samples.vision.face.googlyeyes.ui.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:86)
                                                       at com.google.android.gms.samples.vision.face.googlyeyes.ui.camera.CameraSourcePreview.access$200(CameraSourcePreview.java:31)
                                                       at com.google.android.gms.samples.vision.face.googlyeyes.ui.camera.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:109)

**Comment by hm122** [comment]
Having similar issues, no fix up to now. #246.

**Comment by santhoshgudla** [comment]
I also faced same problem.
Please let me know if any one found the fix for it.
Android version: 5.1.1
Device Model: 2014818 and manufacture: Xiaomi
Exception java.lang.RuntimeException: Fail to connect to camera service
android.hardware.Camera.<init> (Camera.java:533)
android.hardware.Camera.open (Camera.java:365)
com.google.android.gms.vision.CameraSource.zzbjo ()
com.google.android.gms.vision.CameraSource.start ()
com.principalindia.investor.ui.CameraSourcePreview.startIfReady (CameraSourcePreview.java:86)
com.principalindia.investor.ui.CameraSourcePreview.access$200 (CameraSourcePreview.java:31)
com.principalindia.investor.ui.CameraSourcePreview$SurfaceCallback.surfaceCreated (CameraSourcePreview.java:109)
android.view.SurfaceView.updateWindow (SurfaceView.java:581)
android.view.SurfaceView$3.onPreDraw (SurfaceView.java:176)
android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:944)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2014)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1104)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:5962)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:794)
android.view.Choreographer.doCallbacks (Choreographer.java:607)
android.view.Choreographer.doFrame (Choreographer.java:577)

**Comment by midhunceasar** [comment]
I am getting this crash particularly in samsung devices

09-18 15:42:40.305 22133-22133/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 22133
    java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:519)
        at android.hardware.Camera.open(Camera.java:364)
        at com.easym.webrtc.QRCode.camera.CameraSource.createCamera(CameraSource.java:754)
        at com.easym.webrtc.QRCode.camera.CameraSource.start(CameraSource.java:383)
        at com.easym.webrtc.QRCode.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:90)
        at com.easym.webrtc.QRCode.camera.CameraSourcePreview.access$200(CameraSourcePreview.java:32)
        at com.easym.webrtc.QRCode.camera.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:113)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:656)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:172)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2542)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
        at android.view.Choreographer.doCallbacks(Choreographer.java:734)
        at android.view.Choreographer.doFrame(Choreographer.java:670)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by ShamsKeshk** [comment]
**Solved** , I Got the Same Issue  ` java.lang.RuntimeException: Fail to connect to camera service
                                                   at android.hardware.Camera.<init>(Camera.java:497)
                                                   at android.hardware.Camera.open(Camera.java:342)
                                                   at com.google.android.gms.vision.CameraSource.zzchq(Unknown Source)
                                                   at com.google.android.gms.vision.CameraSource.start(Unknown Source) ` , the error was the camera permission , you should use runtime permission to Access Camera .
 To Check if the permission of camera is the error ,After installing the app and it crashed ,Manualy open Setting --> Installed Apps --> get your app and check it's permission , if the camera not have a permission ,go to solve this problem by add Runtime permission .
https://developer.android.com/training/permissions/requesting
