### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Edward0824** [googlesamples/android-vision#240]
java.lang.RuntimeException: Error detecting faces.
                                                             at com.google.android.gms.vision.face.NativeFaceDetectorImpl.detectFacesJni(Native Method)
                                                             at com.google.android.gms.vision.face.NativeFaceDetectorImpl.a(:com.google.android.gms.DynamiteModulesA:16)
                                                             at xu.onTransact(:com.google.android.gms.DynamiteModulesA:20)
                                                             at android.os.Binder.transact(Binder.java:388)
                                                             at com.google.android.gms.internal.zzbgy$zza$zza.zzc(Unknown Source)
                                                             at com.google.android.gms.internal.zzbgt.zzb(Unknown Source)
                                                             at com.google.android.gms.vision.face.FaceDetector.detect(Unknown Source)
                                                             at com.photolab.camera.facedetect.SafeFaceDetector.detect(SafeFaceDetector.java:96)

**Comment by e-beach** [comment]
The maintainers are never going to help you with this little information. You should post the API version at least, and what you were doing when the crash occurred.
