### ISSUE TITLE
Min SDK version 9?

### ISSUE THREAD

**Issue by menjoo** [googlesamples/android-vision#28]
Hi,

I can't get any of the vision samples to work on any device with API 9 till 14.
UnsupportedOperationException every time. (i've updated the Google Play Services on all my devices)
Is the minimum SDK really 9?

**Comment by pm0733464** [comment]
Can you include the stack trace for the UnsupportedOperationException?

**Comment by menjoo** [comment]
This happens when i try to start the multi-tracker sample app on a samsung GT-N7000 running Android 2.3.6:

```
9-21 08:09:49.170    8463-8463/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.UnsupportedOperationException
            at java.nio.DirectByteBuffer.protectedArray(DirectByteBuffer.java:289)
            at java.nio.ByteBuffer.array(ByteBuffer.java:139)
            at com.google.android.gms.vision.CameraSource.zza(Unknown Source)
            at com.google.android.gms.vision.CameraSource.zzBZ(Unknown Source)
            at com.google.android.gms.vision.CameraSource.start(Unknown Source)
            at com.google.android.gms.samples.vision.face.multitracker.ui.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:86)
            at com.google.android.gms.samples.vision.face.multitracker.ui.camera.CameraSourcePreview.access$200(CameraSourcePreview.java:31)
            at com.google.android.gms.samples.vision.face.multitracker.ui.camera.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:109)
            at android.view.SurfaceView.updateWindow(SurfaceView.java:587)
            at android.view.SurfaceView.updateWindow(SurfaceView.java:412)
            at android.view.SurfaceView.dispatchDraw(SurfaceView.java:357)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.View.draw(View.java:7102)
            at android.widget.FrameLayout.draw(FrameLayout.java:357)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.View.draw(View.java:7102)
            at android.widget.FrameLayout.draw(FrameLayout.java:357)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2076)
            at android.view.ViewRoot.draw(ViewRoot.java:1647)
            at android.view.ViewRoot.performTraversals(ViewRoot.java:1380)
            at android.view.ViewRoot.handleMessage(ViewRoot.java:1985)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3691)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by pm0733464** [comment]
Thanks, I'll take a look at this.

**Comment by pm0733464** [comment]
This is fixed in the next release of Google Play Services.
