### ISSUE TITLE
SIGSEGV in libmobile_vision_face.so

### ISSUE THREAD

**Issue by JanZivcak** [googlesamples/android-vision#282]
Hi,
In Google Play Console we can see quite a lot of crashes caused by SIGSEGV from face detector. 
Stack trace shows only native code and we can't reproduce the bug.
There is a lot of crash clusters which are quite similar, the biggest one looks like this:
  - Android 6.0 (but other clusters are also from Android 4.4, Android 5.0)
  - various devices, around 20, most frequent are: j5xnlte, osprey_u2, htc_a16ul
  - signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), dlmalloc_real
  - backtrace:
`1. native: pc 000000000002f4da  /system/lib/libc.so (dlmalloc_real+1193)`
`2. native: pc 00000000000dd59f  /data/data/com.google.android.gms/files/com.google.android.gms.vision/face/libs/armeabi-v7a/libmobile_vision_face.so`
`3. native: pc 00000000000dd7ed  /data/data/com.google.android.gms/files/com.google.android.gms.vision/face/libs/armeabi-v7a/libmobile_vision_face.so`
`4. native: pc 00000000000de549  /data/data/com.google.android.gms/files/com.google.android.gms.vision/face/libs/armeabi-v7a/libmobile_vision_face.so`
`5. native: pc 00000000005a99e3  /data/data/com.google.android.gms/app_chimera/m/00000025/oat/arm/DynamiteModulesA_GmsCore_prodmnc_xhdpi_release.odex`

version: `com.google.android.gms:play-services-vision:9.4.0`

Could you check this? Around 2% of our daily sessisons are affected by this bug so we need to solve this.
Thanks

**Comment by pm0733464** [comment]
This looks like an "out of memory" issue, which can happen if the app holds a lot in memory while calling into the face detector.  I'd suggest looking at your memory usage, and perhaps limiting the resolution of images that you send into the face detector (e.g., downsample images that are very large to smaller images).

**Comment by JanInn** [comment]
Thanks for the answer, it seems reasonable, but:
- malloc returns NULL if it cannot allocate memory, SIGSEGV means different problems with the memory
- we already limit the size of the bitmap which is sent into the face detector, maximum size is set to 1280 kB (e.g. 1131x1131) which doesn't seem big to me
- if there was a problem with memory usage, we would see a lot OutOfMemoryError exceptions from different places of the app, not just this crash in the face detector
- when I don't limit the size of the bitmap sent into the face detector and continuously increase it, the app crashes with this expception, which we don't see in Google Play Console at all:
```
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 15342415 byte allocation with 3693560 free bytes and 3MB until OOM
    at com.google.android.gms.vision.Frame.zzcht(Unknown Source)
    at com.google.android.gms.vision.Frame.getGrayscaleImageData(Unknown Source)
    at com.google.android.gms.vision.face.FaceDetector.detect(Unknown Source)
```
- our app can run in a loop for several hours without any crash even on device with 512 MB, but most of the devices where this crash appeared had 2GB of memory
    
So I'm not sure if this is a problem of high memory usage.
Do you have any other idea?

Maybe we are doing something wrong in general:
- we create the face detector and release it every time we need the face detection, I guess that it's better to have one static global instance of the face detector and reuse it, am I right?
- we are using the face detector within AsyncTask, is this safe?

**Comment by pm0733464** [comment]
The face detector needs to scan the image at different resolutions, in order to find faces of different sizes.  This involves temporarily allocating buffers.  If the app is nearly (but not quite) out of memory, this allocation may be pushing it over the limit.

It's fine to release the face detector every time (as long as no other thread is using it).

Each instance of the face detector is thread safe.  However, if you have multiple instances of the face detector that you are using concurrently, I'm not sure whether this would cause problems (I'm not familiar with all of the details of the native code implementation).  You might try to limit your usage to only one instance, if you aren't already doing so.
