### ISSUE TITLE
Honor 7x given error java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.chimera.DynamiteModuleInitializer"

### ISSUE THREAD

**Issue by KathiriyaHP** [googlesamples/android-vision#354]
Failed to validate DexClassLoader.
                                                                                                     java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.chimera.DynamiteModuleInitializer" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
                                                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                                         at ddb.loadClass(:com.google.android.gms@12673025@12.6.73 (040408-194189626):3)
                                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                         at day.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):22)
                                                                                                         at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):84)
                                                                                                         at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):52)
                                                                                                         at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):117)
                                                                                                         at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):114)
                                                                                                         at ryk.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):13)
                                                                                                         at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext(:com.google.android.gms@12673025@12.6.73 (040408-194189626):18)
                                                                                                         at ryf.onTransact(:com.google.android.gms@12673025@12.6.73 (040408-194189626):12)
                                                                                                         at android.os.Binder.transact(Binder.java:499)
                                                                                                         at com.google.android.gms.internal.zzsc$zza$zza.zza(Unknown Source)
                                                                                                         at com.google.android.gms.internal.zzsb.zza(Unknown Source)
                                                                                                         at com.google.android.gms.internal.zzsb.zza(Unknown Source)
                                                                                                         at com.google.android.gms.vision.barcode.internal.client.zzd.zzchw(Unknown Source)
                                                                                                         at com.google.android.gms.vision.barcode.internal.client.zzd.isOperational(Unknown Source)
                                                                                                         at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source)
                                                                                                         at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
                                                                                                         at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1205)
                                                                                                         at java.lang.Thread.run(Thread.java:776)

**Comment by NoRelect** [comment]
I had the same exception, but resolved it by installing the google play services beta. See my answer on stackoverflow for more information: https://stackoverflow.com/a/50437589/5108100
