### ISSUE TITLE
Crash on "Oppo Lollipop" device, when user rejects Camera permission.

### ISSUE THREAD

**Issue by ali-android** [googlesamples/android-vision#372]
Though permission model is not available in Lollipop devices, but some OEM have introduced in devices below Marshmallow. 

When I used this library on Oppo phone with Lollipop OS, i got following crash.

```
W/ServiceManager( 6535): Permission failure: android.permission.CAMERA from uid=10192 pid=6535
E/CheckPermission( 6535): Permission Denial: can't use camera pid=6535, uid=10192
W/CameraBase( 6535): An error occurred while connecting to camera: 0
E/UncaughtException( 6535): 
E/UncaughtException( 6535): java.lang.RuntimeException: Fail to connect to camera service
E/UncaughtException( 6535): 	at android.hardware.Camera.<init>(Camera.java:542)
E/UncaughtException( 6535): 	at android.hardware.Camera.open(Camera.java:378)
E/UncaughtException( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSource.createCamera(CameraSource.java:602)
E/UncaughtException( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSource.start(CameraSource.java:297)
E/UncaughtException( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:90)
E/UncaughtException( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview.access$200(CameraSourcePreview.java:32)
E/UncaughtException( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:232)
E/UncaughtException( 6535): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
E/UncaughtException( 6535): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
E/UncaughtException( 6535): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
E/UncaughtException( 6535): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2144)
E/UncaughtException( 6535): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
E/UncaughtException( 6535): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6243)
E/UncaughtException( 6535): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
E/UncaughtException( 6535): 	at android.view.Choreographer.doCallbacks(Choreographer.java:586)
E/UncaughtException( 6535): 	at android.view.Choreographer.doFrame(Choreographer.java:556)
E/UncaughtException( 6535): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
E/UncaughtException( 6535): 	at android.os.Handler.handleCallback(Handler.java:739)
E/UncaughtException( 6535): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/UncaughtException( 6535): 	at android.os.Looper.loop(Looper.java:160)
E/UncaughtException( 6535): 	at android.app.ActivityThread.main(ActivityThread.java:5541)
E/UncaughtException( 6535): 	at java.lang.reflect.Method.invoke(Native Method)
E/UncaughtException( 6535): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/UncaughtException( 6535): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/UncaughtException( 6535): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
W/PackageManager(  955): Code path for pkg : com.google.android.googlequicksearchbox changing from /data/app/com.google.android.googlequicksearchbox-1 to /data/app/com.google.android.googlequicksearchbox-2
W/PackageManager(  955): Resource path for pkg : com.google.android.googlequicksearchbox changing from /data/app/com.google.android.googlequicksearchbox-1 to /data/app/com.google.android.googlequicksearchbox-2
W/PackageManager(  955): Unknown permission com.google.android.launcher.permission.CONTENT_REDIRECT in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission com.google.android.voicesearch.SHORTCUTS_ACCESS in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission com.google.android.voicesearch.ACCESS_SETTINGS in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission com.android.browser.permission.PRELOAD in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission com.google.android.ears.permission.WRITE in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission android.permission.FOREGROUND_SERVICE in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission com.google.googlenav.friend.permission.OPT_IN in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission com.google.android.apps.googlevoice.permission.AUTO_SEND in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission com.android.chrome.PRERENDER_URL in package com.google.android.googlequicksearchbox
W/PackageManager(  955): Unknown permission android.permission.USE_FINGERPRINT in package com.google.android.googlequicksearchbox
E/AndroidRuntime( 6535): FATAL EXCEPTION: main
E/AndroidRuntime( 6535): Process: com.nokia.tribe, PID: 6535
E/AndroidRuntime( 6535): java.lang.RuntimeException: Fail to connect to camera service
E/AndroidRuntime( 6535): 	at android.hardware.Camera.<init>(Camera.java:542)
E/AndroidRuntime( 6535): 	at android.hardware.Camera.open(Camera.java:378)
E/AndroidRuntime( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSource.createCamera(CameraSource.java:602)
E/AndroidRuntime( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSource.start(CameraSource.java:297)
E/AndroidRuntime( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:90)
E/AndroidRuntime( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview.access$200(CameraSourcePreview.java:32)
E/AndroidRuntime( 6535): 	at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:232)
E/AndroidRuntime( 6535): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
E/AndroidRuntime( 6535): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
E/AndroidRuntime( 6535): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
E/AndroidRuntime( 6535): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2144)
E/AndroidRuntime( 6535): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
E/AndroidRuntime( 6535): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6243)
E/AndroidRuntime( 6535): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
E/AndroidRuntime( 6535): 	at android.view.Choreographer.doCallbacks(Choreographer.java:586)
E/AndroidRuntime( 6535): 	at android.view.Choreographer.doFrame(Choreographer.java:556)
E/AndroidRuntime( 6535): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
E/AndroidRuntime( 6535): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 6535): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6535): 	at android.os.Looper.loop(Looper.java:160)
E/AndroidRuntime( 6535): 	at android.app.ActivityThread.main(ActivityThread.java:5541)
E/AndroidRuntime( 6535): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6535): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6535): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/AndroidRuntime( 6535): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

**Comment by ali-android** [comment]
I have fixed this issue.
