### ISSUE TITLE
barcode-reader example crashing

### ISSUE THREAD

**Issue by nekhbet** [googlesamples/android-vision#408]
I'm trying to run the barcode-reader example as it is on my Nokia 2.1 running Android 8.1.0 and Google Play Services 15.0.90. The camera starts but no barcode is detected and in the logcat I get (continuously while the camera is working) the following error: 

`2019-02-09 18:17:04.990 3364-3497/com.google.android.gms.samples.vision.barcodereader E/BarcodeNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:8)
        at com.google.android.gms.internal.vision.zzl.zzp(Unknown Source:39)
        at com.google.android.gms.internal.vision.zzl.isOperational(Unknown Source:0)
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:2)
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:16)
        at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1205)
        at java.lang.Thread.run(Thread.java:764)`

What can I do to be able to run it?

Thanks!

**Comment by foozeNZ** [comment]
We have just started experiencing a similar error (No acceptable module found) on the Samsung N9 Lite. Same Android and Google play services versions as you: 8.1.0 and 15.0.90. I installed this demo to help troubleshoot our own app using vision barcode detection which has just stopped working (has been ok until now). We can wait (for native code download), clear data/cache from play services etc without luck (including factory reset). It will just keep repeating:
```

W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:0
E/NativeBarcodeDetectorHandle: Error creating remote native barcode detector
                               com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                   at com.google.android.gms.internal.zzsb.zza(Unknown Source:149)
                                   at com.google.android.gms.vision.barcode.internal.client.zzd.zzchw(Unknown Source:17)
                                   at com.google.android.gms.vision.barcode.internal.client.zzd.isOperational(Unknown Source:0)
                                   at com.google.android.gms.vision.barcode.internal.client.zzd.zza(Unknown Source:1)
                                   at com.google.android.gms.vision.barcode.BarcodeDetector.detect(Unknown Source:60)
                                   at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:30)
                                   at com.google.android.gms.samples.vision.barcodereader.ui.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1205)
                                   at java.lang.Thread.run(Thread.java:764)
```

**Comment by polesapart** [comment]
I have issues on Moto E5 (Android Go 8.1) as well.

**Comment by caiiicaiii** [comment]
Does someone already fix this issue?
I am experiencing the same issue

E/NativeBarcodeDetectorHandle: Error creating remote native barcode detector
    com.google.android.gms.internal.zzsb$zza: Remote load failed. No local fallback found.
