### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to resume activity {com.coreceptionist.android/com.coreceptionist.android.activity.CameraCaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.coreceptionist.android.faceTracker.CameraSourcePreview.start(com.google.android.gms.vision.CameraSource, com.coreceptionist.android.faceTracker.GraphicOverlay)' on a null object reference

### ISSUE THREAD

**Issue by ervishu83** [googlesamples/android-vision#417]
`Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.coreceptionist.android/com.coreceptionist.android.activity.CameraCaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.coreceptionist.android.faceTracker.CameraSourcePreview.start(com.google.android.gms.vision.CameraSource, com.coreceptionist.android.faceTracker.GraphicOverlay)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3584)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2865)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by kopilim96** [comment]
1 of the exception u facing is NullPointerException. u can look through your code again or post your source code here.
