### ISSUE TITLE
How to make the Android vision support "Android Go OS devices 

### ISSUE THREAD

**Issue by Phahlane** [googlesamples/android-vision#437]
My app needs to support Android Go OS devices but it doesn't scan the QR code on those devices but works well in other OS

**Comment by sisaj** [comment]
Also experiencing the same issue, Stack Trace error log below (Logcat flooded with this mee):
`E/BarcodeNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:8)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source:28)
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source:9)
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:23)
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:12)
        at com.myUrl.myExampleApp.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1205)
        at java.lang.Thread.run(Thread.java:764)`

line 1205 is: mDetector.receiveFrame(outputFrame) from below;
`
                try {
                    mDetector.receiveFrame(outputFrame);
                } catch (Throwable t) {
                    Log.e(TAG, "Exception thrown from receiver.", t);
                } finally {
                    mCamera.addCallbackBuffer(data.array());
                }`
