### ISSUE TITLE
Callback buffer was too small

### ISSUE THREAD

**Issue by malloth** [googlesamples/android-vision#47]
In Google Play Services 8.3, when I start CameraSource built with CameraSource.Builder.setRequestedPreviewSize(640, 480) I get the following exception:

E/Camera-JNI: Callback buffer was too small! Expected 1382400 bytes, but got 460801 bytes!
11-06 12:23:35.560 151-151/? E/: Qvoid android::disable_msg_type(camera_device*, int32_t): E
11-06 12:23:35.560 151-151/? E/: disableMsgType: E
11-06 12:23:35.560 151-151/? E/: disableMsgType: X, msgType =0x10, mMsgEnabled=0xd
11-06 12:23:35.580 151-28672/? V/:  newFrame =0x40850b2c, frm_type = 1
11-06 12:23:35.580 151-28672/? V/: int android::QCameraHardwareInterface::cache_ops(int, ion_flush_data*, int): Cache OPs type(1082438032) success
com.mayer.esale E/AndroidRuntime: FATAL EXCEPTION: Thread-328
com.mayer.esale E/AndroidRuntime: java.lang.IllegalArgumentException: Null image data supplied.
com.mayer.esale E/AndroidRuntime:     at com.google.android.gms.vision.Frame$Builder.setImageData(Unknown Source)
com.mayer.esale E/AndroidRuntime:     at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
com.mayer.esale E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)

This happens only on one of my devices: Kruger & Matz MOVE.
Some other preview sizes are working (like: 1024x768, 1600x1200). 

It was working correctly in Google Play Services 8.1.

My guess is that you use Camera.addCallbackBuffer() with byte array of an invalid length. Previous buffer size computing method was correct - at least for this particular device.

**Comment by pm0733464** [comment]
There's an open source version of CameraSource here:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java

Can you print out the preview size and buffer sizes computed here with this device?:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java#L1026

**Comment by malloth** [comment]
Preview: width = 640, height = 480. Buffer size: 460801. What's strange is that it somehow works now...
