### ISSUE TITLE
Intermittent crash when turning screen off and on again

### ISSUE THREAD

**Issue by bherbst** [googlesamples/android-vision#60]
We discovered a crash in our own app when locking and unlocking the screen, and we have confirmed it exists in the barcode-reader sample as well.

Note that so far I have only seen this with Play Services 8.4, but due to the intermittent nature of this bug it is hard to determine whether it is actually new in 8.4.

Steps to reproduce:
 1. Open the barcode sample and go to the "read barcode" screen
 2. Lock the device's screen
 3. Unlock the device's screen

Observe that sometimes the app will crash with the following exception:

    01-07 14:36:11.880 18763-22433/? E/Signal: Caught Unhandled Exception
        java.lang.IllegalArgumentException: Null image data supplied.
            at com.google.android.gms.vision.Frame$Builder.setImageData(Unknown Source)
            at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
            at java.lang.Thread.run(Thread.java:818)
    01-07 14:36:11.984 18763-22433/? E/AndroidRuntime: FATAL EXCEPTION: Thread-6576
        java.lang.IllegalArgumentException: Null image data supplied.
            at com.google.android.gms.vision.Frame$Builder.setImageData(Unknown Source)
            at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
            at java.lang.Thread.run(Thread.java:818)

**Comment by pchx** [comment]
What device are you seeing the crash on? Have you tried other devices?

I wasn't able to reproduce this issue on a Nexus 5.

**Comment by bherbst** [comment]
I wasn't able to reproduce on my Nexus 5 either.

I was able to reproduce on both a Moto X Style and a Nexus 6P.

**Comment by pchx** [comment]
We'll have to get some phones to test on, but it sounds like a camera driver problem.

**Comment by anothem** [comment]
Not sure if this is helpful, but I'm experiencing something similar on the Nexus 5X. On a certain event I stop the camera source and start it again after about a second. Sometimes I get this crash. 

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-20127
                               Process: com.yplanapp.ticketing, PID: 11652
                               java.lang.IllegalArgumentException: Null image data supplied.
                                     at com.google.android.gms.vision.Frame$Builder.setImageData(Unknown Source)
                                     at com.yplanapp.ticketing.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1212)
                                     at java.lang.Thread.run(Thread.java:818)
```

**Comment by pm0733464** [comment]
@anothem - I see that you are using the open source version of CameraSource.  Can you try the following to help us to track down this problem?:

On this line:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java#L1152

Change the "if" to a "while".  I think that this will fix it.

But it's possible that there's a deeper issue.  Please also add the debugging statement below here in the code, and let us know if you see any of these warnings logged:

https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java#L1125

if (mPendingFrameData == null) {
  if (data == null) {
    Log.w(TAG, "Null image data received from the camera.");
  } else if (mBytesToByteBuffer.containsKey(data)) {
    Log.w(TAG, "mBytesToByteBuffer has a null entry for image data received from the camera.");
  } else {
    Log.w(TAG, "Could not find ByteBuffer associated with the image data from the camera.");
  }
}

Thanks.

**Comment by anothem** [comment]
Hi @pm0733464, thanks for the quick response!
I've tried changing the `if` to a `while` and it does seem to solve it, I haven't been able to crash it once. Keeping in mind though that I'm only seeing the crash intermittently, so it's not the most reliable test.

I've added the logs above, the only one I've seen is the following (but this I've seen multiple times)
```
01-15 16:27:32.370 21031-21031/com.yplanapp.ticketing W/CameraSource$FrameProcessingRunnable: Could not find ByteBuffer associated with the image data from the camera.
```

**Comment by pm0733464** [comment]
Thanks.  I'll look into this some more.

**Comment by vkislicins** [comment]
Seeing the same problem - mPendingFrameData is always null. Tried on Nexus 6P and Samsung Galaxy S4, with Play Services 8.4 and 8.3

**Comment by pm0733464** [comment]
As a near term workaround, I'd recommend using the open source version and changing the "if" to a "while", as I suggested above.  

We will fix this in a future release.

**Comment by orcuns** [comment]
I have encountered the same issue while using facetracker library on my nexus 6p and samsung galaxy sm-t230. Is there any near future release to fix this issue? Should I implement Play Services manually to my project and change CameraSource.class "if" to a "while" or wait a new release of play services? Thanks

**Comment by pm0733464** [comment]
Make the "if" / "while" change.  There's an open source copy of CameraSource that I linked to above, and you'd use that in your project in place of com.google.android.gms.vision.CameraSource (i.e., copy the file and change the package name).  

Note that I have a change pending to fix the issue in the open source version, if you'd prefer to wait.

**Comment by pm0733464** [comment]
We have updated the open source version of the code with the fix:

[](https://github.com/googlesamples/android-vision/blob/master/visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java)

**Comment by herrskytte** [comment]
We are still using the open source version in our app. Any idea when the fix will make it's way to Play Services version?

**Comment by KoKoHtun** [comment]
My used of Play Service's Version_  9.6.83(248_133155058)
So,thank's..!
Please,  You're supporting helful me.

**Comment by pm0733464** [comment]
This was fixed in the Play Services version.

**Comment by webermax** [comment]
I can confirm open source CameraSource.java working well.
Any hint on how to use the correct version of play services?
