### ISSUE TITLE
Camera service died!, error 100

### ISSUE THREAD

**Issue by cpena** [googlesamples/android-vision#82]
Hi,
I'm using CameraSource from visionSamples/barcode-reader/app/src/main/java/com/google/android/gms/samples/vision/barcodereader/ui/camera/CameraSource.java to process, with my own detector/processor (currently doing nothing) and taking pictures every 5 minutes (running in a service).

After around 8 hours, when a try to take a picture, I get:

**W/CameraBase: Camera service died!
W/CameraBase: mediaserver's remote binder Camera object died
E/Camera: Error 100**

I add a camera error callback to get the error and restart the service:
`camera.setErrorCallback(new Camera.ErrorCallback() {
            @Override
            public void onError(int error, Camera camera) {
                Log.e(TAG,"Camera error: "+error);

                if(error == Camera.CAMERA_ERROR_SERVER_DIED) {
                    try {
                        stop();
                        start();
                    }
                    catch(Exception e){
                        Log.e(TAG,"Exception restarting camera",e);
                    }
                }
            }
        });`

But I get this exception:
**D/Camera: app passed NULL surface
I/ServiceManager: Waiting for service media.camera...
E/OpenCameraSource: No supported preview sizes
E/OpenCameraSource: Exception restarting camera
                                                                              java.lang.RuntimeException: Could not find suitable preview size.**

Then, I try to restart the app, but I get:

**03-18 10:09:33.883 18298-18298/cl.visualprogress.timelapser W/CameraBase: An error occurred while connecting to camera: 0
03-18 10:09:33.899 18298-18298/cl.visualprogress.timelapser E/VisionService: startCamera Exception: Fail to connect to camera service
                                                                             java.lang.RuntimeException: Fail to connect to camera service
                                                                                 at android.hardware.Camera.<init>(Camera.java:497)
                                                                                 at android.hardware.Camera.open(Camera.java:342)
                                                                                 at cl.visualprogress.timelapser.utils.CameraSource.createCamera(CameraSource.java:768)
                                                                                 at cl.visualprogress.timelapser.utils.CameraSource.start(CameraSource.java:359)
                                                                                 at cl.visualprogress.timelapser.services.VisionService.startCamera(VisionService.java:78)
                                                                                 at cl.visualprogress.timelapser.services.VisionService.onStartCommand(VisionService.java:43)
                                                                                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
                                                                                 at android.app.ActivityThread.access$2100(ActivityThread.java:151)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)**

I need to restart the phone to get the camera work again.
Can someone help me?

**Comment by pm0733464** [comment]
What type of phone are you using?

It looks like a native crash in the mediaserver for the device.  Once that crashed, it wasn't possible to restart the camera (e.g., it could not get the list of available preview sizes).

Is there a native stack trace in the logs?  We'd need that as well as the phone type in order to investigate further.

Issues like this tend to be device-specific, so you probably wouldn't run into the same issue if you use a different type of phone.

**Comment by pm0733464** [comment]
I'd suggest generating an Android bug report from the phone when the crash happens again.

1.  In Settings, go to Developer Options.
2.  Press "Take bug report".
3.  Wait for the report to generate, and you'll be able to mail the report to yourself.

This bug report should include the native stack trace.

**Comment by cpena** [comment]
Thanks @pm0733464 
My phone is Nexus 4, android 5.1.1

The logs with native stack trace:
**22:44:48.630 28128-28128/cl.visualprogress.timelapser D/MainService: Servicio principal iniciado
03-18 22:44:48.713 28128-28219/cl.visualprogress.timelapser I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/15/15, ab0075f, Id3510ff6dc
03-18 22:44:48.716 28128-28219/cl.visualprogress.timelapser I/OpenGLRenderer: Initialized EGL, version 1.4
03-18 22:44:48.760 28128-28219/cl.visualprogress.timelapser D/OpenGLRenderer: Enabling debug mode 0
03-18 22:44:48.810 28128-28128/cl.visualprogress.timelapser D/SyncService: Iniciando servicio de sincronizacion
03-18 22:44:49.015 28128-28128/cl.visualprogress.timelapser D/SyncService: Esperando tareas
03-18 22:44:49.016 28128-28128/cl.visualprogress.timelapser D/VisionService: Iniciando servicio de vision
03-18 22:44:49.022 14470-14491/? W/AudioFlinger: acquireAudioSessionId() unknown client 28128 for session 121
03-18 22:44:49.054 14470-14491/? W/AudioFlinger: acquireAudioSessionId() unknown client 28128 for session 122
03-18 22:44:49.081 14470-14491/? I/CameraClient: Opening camera 0
03-18 22:44:51.239 28128-28138/cl.visualprogress.timelapser W/art: Suspending all threads took: 5.066ms
03-18 22:44:51.553 572-594/? W/ProcessCpuTracker: Skipping unknown process pid 28285
03-18 22:44:51.555 572-594/? W/ProcessCpuTracker: Skipping unknown process pid 28287
03-18 22:44:51.618 572-599/? W/WindowManager: App freeze timeout expired.
03-18 22:44:51.619 572-599/? W/WindowManager: Force clearing freeze: AppWindowToken{2f2219f0 token=Token{12b3233 ActivityRecord{a7245a2 u0 cl.visualprogress.timelapser/.activities.MainActivity t161}}}
03-18 22:44:56.492 572-594/? W/ActivityManager: Launch timeout has expired, giving up wake lock!
03-18 22:44:57.276 1941-2021/? D/HeadsetStateMachine: Disconnected process message: 10, size: 0
03-18 22:44:58.998 572-654/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=6,77 rxSuccessRate=6,52 targetRoamBSSID=00:00:00:00:00:00 RSSI=-44
03-18 22:44:58.998 572-654/? E/WifiStateMachine: WifiStateMachine starting scan for "chanvaflo"WPA_PSK with 2412
03-18 22:44:59.116 14470-14491/? E/QCameraHWI: startCamera: cam_ops_open failed: id = 0
03-18 22:44:59.116 14470-14491/? I/QCameraHWI: virtual android::QCameraHardwareInterface::~QCameraHardwareInterface() First stop the polling threads before deleting instances
03-18 22:44:59.117 14470-14491/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x80000764 in tid 14491 (Binder_1)
03-18 22:44:59.230 572-675/? W/NativeCrashListener: Couldn't find ProcessRecord for pid 14470
03-18 22:44:59.242 184-184/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-18 22:44:59.243 184-184/? E/DEBUG: AM write failure (32 / Broken pipe)
03-18 22:44:59.243 184-184/? I/DEBUG: Build fingerprint: 'google/occam/mako:5.1.1/LMY48M/2167285:user/release-keys'
03-18 22:44:59.243 184-184/? I/DEBUG: Revision: '11'
03-18 22:44:59.243 184-184/? I/DEBUG: ABI: 'arm'
03-18 22:44:59.244 184-184/? I/DEBUG: pid: 14470, tid: 14491, name: Binder_1  >>> /system/bin/mediaserver <<<
03-18 22:44:59.244 184-184/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x80000764
03-18 22:44:59.314 184-184/? I/DEBUG:     r0 80000664  r1 00001000  r2 00000003  r3 00000000
03-18 22:44:59.314 184-184/? I/DEBUG:     r4 80000664  r5 80000664  r6 b704a7c4  r7 00000000
03-18 22:44:59.314 184-184/? I/DEBUG:     r8 b61fc844  r9 b704a2d8  sl 00000000  fp 00000000
03-18 22:44:59.314 184-184/? I/DEBUG:     ip 00000000  sp b55959f0  lr b6f814a1  pc b6f812b6  cpsr 00070030
03-18 22:44:59.314 184-184/? I/DEBUG:     #00 pc 000032b6  /system/bin/linker (__dl__ZL13soinfo_unloadP6soinfo+5)
03-18 22:44:59.314 184-184/? I/DEBUG:     #01 pc 0000349d  /system/bin/linker (__dl__Z10do_dlcloseP6soinfo+12)
03-18 22:44:59.314 184-184/? I/DEBUG:     #02 pc 00001077  /system/bin/linker (__dl_dlclose+22)
03-18 22:44:59.314 184-184/? I/DEBUG:     #03 pc 00019ee5  /system/lib/hw/camera.mako.so (android::QCameraHardwareInterface::~QCameraHardwareInterface()+188)
03-18 22:44:59.314 184-184/? I/DEBUG:     #04 pc 0001a0bd  /system/lib/hw/camera.mako.so (android::QCameraHardwareInterface::~QCameraHardwareInterface()+4)
03-18 22:44:59.314 184-184/? I/DEBUG:     #05 pc 0001fd39  /system/lib/hw/camera.mako.so (camera_device_open+240)
03-18 22:44:59.315 184-184/? I/DEBUG:     #06 pc 0004c97d  /system/lib/libcameraservice.so
03-18 22:44:59.315 184-184/? I/DEBUG:     #07 pc 0004dfbd  /system/lib/libcameraservice.so (android::CameraClient::initialize(camera_module*)+156)
03-18 22:44:59.315 184-184/? I/DEBUG:     #08 pc 00046a79  /system/lib/libcameraservice.so (android::CameraService::connectFinishUnsafe(android::sp<android::CameraService::BasicClient> const&, android::sp<android::IBinder> const&)+16)
03-18 22:44:59.315 184-184/? I/DEBUG:     #09 pc 0004838f  /system/lib/libcameraservice.so (android::CameraService::connectHelperLocked(android::sp<android::CameraService::Client>&, android::sp<android::ICameraClient> const&, int, android::String16 const&, int, int, int, bool)+394)
03-18 22:44:59.315 184-184/? I/DEBUG:     #10 pc 000484e5  /system/lib/libcameraservice.so (android::CameraService::connect(android::sp<android::ICameraClient> const&, int, android::String16 const&, int, android::sp<android::ICamera>&)+176)
03-18 22:44:59.315 184-184/? I/DEBUG:     #11 pc 000249f9  /system/lib/libcamera_client.so (android::BnCameraService::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+420)
03-18 22:44:59.315 184-184/? I/DEBUG:     #12 pc 00045ea5  /system/lib/libcameraservice.so (android::CameraService::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+120)
03-18 22:44:59.315 184-184/? I/DEBUG:     #13 pc 0001a6cd  /system/lib/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+60)
03-18 22:44:59.315 184-184/? I/DEBUG:     #14 pc 0001f77b  /system/lib/libbinder.so (android::IPCThreadState::executeCommand(int)+582)
03-18 22:44:59.315 184-184/? I/DEBUG:     #15 pc 0001f89f  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+38)
03-18 22:44:59.315 184-184/? I/DEBUG:     #16 pc 0001f8e1  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+48)
03-18 22:44:59.315 184-184/? I/DEBUG:     #17 pc 00023a5f  /system/lib/libbinder.so
03-18 22:44:59.315 184-184/? I/DEBUG:     #18 pc 000104d5  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112)
03-18 22:44:59.315 184-184/? I/DEBUG:     #19 pc 00010045  /system/lib/libutils.so
03-18 22:44:59.315 184-184/? I/DEBUG:     #20 pc 00016173  /system/lib/libc.so (__pthread_start(void*)+30)
03-18 22:44:59.315 184-184/? I/DEBUG:     #21 pc 0001409b  /system/lib/libc.so (__start_thread+6)
03-18 22:44:59.791 27290-27306/? W/AudioSystem: AudioPolicyService server died!
03-18 22:44:59.791 27290-27306/? W/AudioSystem: AudioFlinger server died!
03-18 22:44:59.792 572-1280/? W/AudioSystem: AudioPolicyService server died!
03-18 22:44:59.792 572-1280/? W/AudioSystem: AudioFlinger server died!
03-18 22:44:59.792 28128-28128/cl.visualprogress.timelapser W/CameraBase: An error occurred while connecting to camera: 0
03-18 22:44:59.793 26135-26150/? W/AudioSystem: AudioPolicyService server died!
03-18 22:44:59.793 169-169/? I/ServiceManager: service 'media.audio_policy' died
03-18 22:44:59.793 171-1985/? W/IMediaDeathNotifier: media server died
03-18 22:44:59.793 169-169/? I/ServiceManager: service 'media.audio_flinger' died
03-18 22:44:59.793 28128-28144/cl.visualprogress.timelapser W/CameraBase: Camera service died!
03-18 22:44:59.793 169-169/? I/ServiceManager: service 'media.player' died
03-18 22:44:59.794 169-169/? I/ServiceManager: service 'media.camera' died
03-18 22:44:59.794 169-169/? I/ServiceManager: service 'media.sound_trigger_hw' died
03-18 22:44:59.794 27290-27401/? W/AudioRecord: dead IAudioRecord, creating a new one from obtainBuffer()
03-18 22:44:59.794 572-661/? E/AudioService: Media server died.
03-18 22:44:59.795 27290-27401/? I/ServiceManager: Waiting for service media.audio_flinger...
03-18 22:44:59.798 572-595/? I/BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
03-18 22:44:59.809 28128-28128/cl.visualprogress.timelapser E/VisionService: startCamera Exception: Fail to connect to camera service
                                                                             java.lang.RuntimeException: Fail to connect to camera service
                                                                                 at android.hardware.Camera.<init>(Camera.java:497)
                                                                                 at android.hardware.Camera.open(Camera.java:342)
                                                                                 at cl.visualprogress.timelapser.utils.CameraSource.createCamera(CameraSource.java:768)
                                                                                 at cl.visualprogress.timelapser.utils.CameraSource.start(CameraSource.java:359)
                                                                                 at cl.visualprogress.timelapser.services.VisionService.startCamera(VisionService.java:78)
                                                                                 at cl.visualprogress.timelapser.services.VisionService.onStartCommand(VisionService.java:43)
                                                                                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
                                                                                 at android.app.ActivityThread.access$2100(ActivityThread.java:151)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
03-18 22:44:59.814 572-595/? W/DropBoxManagerService: Dropping: SYSTEM_TOMBSTONE (10 > 0 bytes)**

[bugreport-2016-03-18-22-45-56.txt](https://github.com/googlesamples/android-vision/files/180610/bugreport-2016-03-18-22-45-56.txt)

Best regards

**Comment by pm0733464** [comment]
Thanks, we will take a look.

**Comment by pm0733464** [comment]
Note that this issue is with the Nexus 4 camera specifically, rather than the mobile vision API.  I spoke with someone on the camera team, and he took a look at the bug report and found the associated crash.  

Unfortunately, the Nexus 4 is out of support (didn't receive Android 6.0), so we have no way to fix issues on it at this point.

As a workaround, something that you might try would be to periodically stop and restart the camera (e.g., after every time you take the picture).  This might avoid the issue if the problem is triggered by very long runs of the Nexus 4 camera.

**Comment by cpena** [comment]
Thanks, Paul.
